version: "3.4"

services:
  backend:
    build: ./backend
    ports:
      - "8080:80"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost:8080